/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateComment201Response,
  CreateCommentRequest,
  GetReplies200Response,
} from '../models/index';
import {
    CreateComment201ResponseFromJSON,
    CreateComment201ResponseToJSON,
    CreateCommentRequestFromJSON,
    CreateCommentRequestToJSON,
    GetReplies200ResponseFromJSON,
    GetReplies200ResponseToJSON,
} from '../models/index';

export interface CreateCommentOperationRequest {
    whatToDiscardProblemId: string;
    createCommentRequest?: CreateCommentRequest;
}

export interface DeleteCommentRequest {
    whatToDiscardProblemId: string;
    id: string;
}

export interface GetCommentsRequest {
    whatToDiscardProblemId: string;
}

/**
 * 
 */
export class WhatToDiscardProblemCommentApi extends runtime.BaseAPI {

    /**
     * create comment
     */
    async createCommentRaw(requestParameters: CreateCommentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateComment201Response>> {
        if (requestParameters['whatToDiscardProblemId'] == null) {
            throw new runtime.RequiredError(
                'whatToDiscardProblemId',
                'Required parameter "whatToDiscardProblemId" was null or undefined when calling createComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/what_to_discard_problems/{what_to_discard_problem_id}/comments`.replace(`{${"what_to_discard_problem_id"}}`, encodeURIComponent(String(requestParameters['whatToDiscardProblemId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCommentRequestToJSON(requestParameters['createCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateComment201ResponseFromJSON(jsonValue));
    }

    /**
     * create comment
     */
    async createComment(requestParameters: CreateCommentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateComment201Response> {
        const response = await this.createCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Comment
     */
    async deleteCommentRaw(requestParameters: DeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['whatToDiscardProblemId'] == null) {
            throw new runtime.RequiredError(
                'whatToDiscardProblemId',
                'Required parameter "whatToDiscardProblemId" was null or undefined when calling deleteComment().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/what_to_discard_problems/{what_to_discard_problem_id}/comments/{id}`.replace(`{${"what_to_discard_problem_id"}}`, encodeURIComponent(String(requestParameters['whatToDiscardProblemId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Comment
     */
    async deleteComment(requestParameters: DeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCommentRaw(requestParameters, initOverrides);
    }

    /**
     * list comments
     */
    async getCommentsRaw(requestParameters: GetCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetReplies200Response>> {
        if (requestParameters['whatToDiscardProblemId'] == null) {
            throw new runtime.RequiredError(
                'whatToDiscardProblemId',
                'Required parameter "whatToDiscardProblemId" was null or undefined when calling getComments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/what_to_discard_problems/{what_to_discard_problem_id}/comments`.replace(`{${"what_to_discard_problem_id"}}`, encodeURIComponent(String(requestParameters['whatToDiscardProblemId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetReplies200ResponseFromJSON(jsonValue));
    }

    /**
     * list comments
     */
    async getComments(requestParameters: GetCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetReplies200Response> {
        const response = await this.getCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
