/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateLike201Response,
} from '../models/index';
import {
    CreateLike201ResponseFromJSON,
    CreateLike201ResponseToJSON,
} from '../models/index';

export interface CreateLikeRequest {
    whatToDiscardProblemId: string;
}

export interface DeleteLikeRequest {
    whatToDiscardProblemId: string;
    id: string;
}

/**
 * 
 */
export class WhatToDiscardProblemLikeApi extends runtime.BaseAPI {

    /**
     * Create Like
     */
    async createLikeRaw(requestParameters: CreateLikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateLike201Response>> {
        if (requestParameters['whatToDiscardProblemId'] == null) {
            throw new runtime.RequiredError(
                'whatToDiscardProblemId',
                'Required parameter "whatToDiscardProblemId" was null or undefined when calling createLike().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/what_to_discard_problems/{what_to_discard_problem_id}/likes`.replace(`{${"what_to_discard_problem_id"}}`, encodeURIComponent(String(requestParameters['whatToDiscardProblemId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateLike201ResponseFromJSON(jsonValue));
    }

    /**
     * Create Like
     */
    async createLike(requestParameters: CreateLikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateLike201Response> {
        const response = await this.createLikeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Like
     */
    async deleteLikeRaw(requestParameters: DeleteLikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['whatToDiscardProblemId'] == null) {
            throw new runtime.RequiredError(
                'whatToDiscardProblemId',
                'Required parameter "whatToDiscardProblemId" was null or undefined when calling deleteLike().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteLike().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/what_to_discard_problems/{what_to_discard_problem_id}/likes/{id}`.replace(`{${"what_to_discard_problem_id"}}`, encodeURIComponent(String(requestParameters['whatToDiscardProblemId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Like
     */
    async deleteLike(requestParameters: DeleteLikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLikeRaw(requestParameters, initOverrides);
    }

}
