/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCommentRequestWhatToDiscardProblemComment } from './CreateCommentRequestWhatToDiscardProblemComment';
import {
    CreateCommentRequestWhatToDiscardProblemCommentFromJSON,
    CreateCommentRequestWhatToDiscardProblemCommentFromJSONTyped,
    CreateCommentRequestWhatToDiscardProblemCommentToJSON,
    CreateCommentRequestWhatToDiscardProblemCommentToJSONTyped,
} from './CreateCommentRequestWhatToDiscardProblemComment';

/**
 * 
 * @export
 * @interface CreateCommentRequest
 */
export interface CreateCommentRequest {
    /**
     * 
     * @type {CreateCommentRequestWhatToDiscardProblemComment}
     * @memberof CreateCommentRequest
     */
    whatToDiscardProblemComment: CreateCommentRequestWhatToDiscardProblemComment;
}

/**
 * Check if a given object implements the CreateCommentRequest interface.
 */
export function instanceOfCreateCommentRequest(value: object): value is CreateCommentRequest {
    if (!('whatToDiscardProblemComment' in value) || value['whatToDiscardProblemComment'] === undefined) return false;
    return true;
}

export function CreateCommentRequestFromJSON(json: any): CreateCommentRequest {
    return CreateCommentRequestFromJSONTyped(json, false);
}

export function CreateCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'whatToDiscardProblemComment': CreateCommentRequestWhatToDiscardProblemCommentFromJSON(json['what_to_discard_problem_comment']),
    };
}

export function CreateCommentRequestToJSON(json: any): CreateCommentRequest {
    return CreateCommentRequestToJSONTyped(json, false);
}

export function CreateCommentRequestToJSONTyped(value?: CreateCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'what_to_discard_problem_comment': CreateCommentRequestWhatToDiscardProblemCommentToJSON(value['whatToDiscardProblemComment']),
    };
}

