/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * 
 * @export
 * @interface CreateComment201Response
 */
export interface CreateComment201Response {
    /**
     * 
     * @type {Comment}
     * @memberof CreateComment201Response
     */
    comment: Comment;
}

/**
 * Check if a given object implements the CreateComment201Response interface.
 */
export function instanceOfCreateComment201Response(value: object): value is CreateComment201Response {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function CreateComment201ResponseFromJSON(json: any): CreateComment201Response {
    return CreateComment201ResponseFromJSONTyped(json, false);
}

export function CreateComment201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateComment201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': CommentFromJSON(json['comment']),
    };
}

export function CreateComment201ResponseToJSON(json: any): CreateComment201Response {
    return CreateComment201ResponseToJSONTyped(json, false);
}

export function CreateComment201ResponseToJSONTyped(value?: CreateComment201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': CommentToJSON(value['comment']),
    };
}

