/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentRequestWhatToDiscardProblemComment
 */
export interface CreateCommentRequestWhatToDiscardProblemComment {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentRequestWhatToDiscardProblemComment
     */
    parentCommentId: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentRequestWhatToDiscardProblemComment
     */
    content: string;
}

/**
 * Check if a given object implements the CreateCommentRequestWhatToDiscardProblemComment interface.
 */
export function instanceOfCreateCommentRequestWhatToDiscardProblemComment(value: object): value is CreateCommentRequestWhatToDiscardProblemComment {
    if (!('parentCommentId' in value) || value['parentCommentId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateCommentRequestWhatToDiscardProblemCommentFromJSON(json: any): CreateCommentRequestWhatToDiscardProblemComment {
    return CreateCommentRequestWhatToDiscardProblemCommentFromJSONTyped(json, false);
}

export function CreateCommentRequestWhatToDiscardProblemCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentRequestWhatToDiscardProblemComment {
    if (json == null) {
        return json;
    }
    return {
        
        'parentCommentId': json['parent_comment_id'],
        'content': json['content'],
    };
}

export function CreateCommentRequestWhatToDiscardProblemCommentToJSON(json: any): CreateCommentRequestWhatToDiscardProblemComment {
    return CreateCommentRequestWhatToDiscardProblemCommentToJSONTyped(json, false);
}

export function CreateCommentRequestWhatToDiscardProblemCommentToJSONTyped(value?: CreateCommentRequestWhatToDiscardProblemComment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parent_comment_id': value['parentCommentId'],
        'content': value['content'],
    };
}

