/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Like } from './Like';
import {
    LikeFromJSON,
    LikeFromJSONTyped,
    LikeToJSON,
    LikeToJSONTyped,
} from './Like';

/**
 * 
 * @export
 * @interface CreateLike201ResponseWhatToDiscardProblemLike
 */
export interface CreateLike201ResponseWhatToDiscardProblemLike {
    /**
     * 
     * @type {Like}
     * @memberof CreateLike201ResponseWhatToDiscardProblemLike
     */
    myLike: Like;
}

/**
 * Check if a given object implements the CreateLike201ResponseWhatToDiscardProblemLike interface.
 */
export function instanceOfCreateLike201ResponseWhatToDiscardProblemLike(value: object): value is CreateLike201ResponseWhatToDiscardProblemLike {
    if (!('myLike' in value) || value['myLike'] === undefined) return false;
    return true;
}

export function CreateLike201ResponseWhatToDiscardProblemLikeFromJSON(json: any): CreateLike201ResponseWhatToDiscardProblemLike {
    return CreateLike201ResponseWhatToDiscardProblemLikeFromJSONTyped(json, false);
}

export function CreateLike201ResponseWhatToDiscardProblemLikeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLike201ResponseWhatToDiscardProblemLike {
    if (json == null) {
        return json;
    }
    return {
        
        'myLike': LikeFromJSON(json['myLike']),
    };
}

export function CreateLike201ResponseWhatToDiscardProblemLikeToJSON(json: any): CreateLike201ResponseWhatToDiscardProblemLike {
    return CreateLike201ResponseWhatToDiscardProblemLikeToJSONTyped(json, false);
}

export function CreateLike201ResponseWhatToDiscardProblemLikeToJSONTyped(value?: CreateLike201ResponseWhatToDiscardProblemLike | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'myLike': LikeToJSON(value['myLike']),
    };
}

