/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateLike201ResponseWhatToDiscardProblemLike } from './CreateLike201ResponseWhatToDiscardProblemLike';
import {
    CreateLike201ResponseWhatToDiscardProblemLikeFromJSON,
    CreateLike201ResponseWhatToDiscardProblemLikeFromJSONTyped,
    CreateLike201ResponseWhatToDiscardProblemLikeToJSON,
    CreateLike201ResponseWhatToDiscardProblemLikeToJSONTyped,
} from './CreateLike201ResponseWhatToDiscardProblemLike';

/**
 * 
 * @export
 * @interface CreateLike201Response
 */
export interface CreateLike201Response {
    /**
     * 
     * @type {CreateLike201ResponseWhatToDiscardProblemLike}
     * @memberof CreateLike201Response
     */
    whatToDiscardProblemLike?: CreateLike201ResponseWhatToDiscardProblemLike;
}

/**
 * Check if a given object implements the CreateLike201Response interface.
 */
export function instanceOfCreateLike201Response(value: object): value is CreateLike201Response {
    return true;
}

export function CreateLike201ResponseFromJSON(json: any): CreateLike201Response {
    return CreateLike201ResponseFromJSONTyped(json, false);
}

export function CreateLike201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLike201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'whatToDiscardProblemLike': json['what_to_discard_problem_like'] == null ? undefined : CreateLike201ResponseWhatToDiscardProblemLikeFromJSON(json['what_to_discard_problem_like']),
    };
}

export function CreateLike201ResponseToJSON(json: any): CreateLike201Response {
    return CreateLike201ResponseToJSONTyped(json, false);
}

export function CreateLike201ResponseToJSONTyped(value?: CreateLike201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'what_to_discard_problem_like': CreateLike201ResponseWhatToDiscardProblemLikeToJSON(value['whatToDiscardProblemLike']),
    };
}

