/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * 
 * @export
 * @interface GetComments200Response
 */
export interface GetComments200Response {
    /**
     * 
     * @type {Array<Comment>}
     * @memberof GetComments200Response
     */
    comments: Array<Comment>;
}

/**
 * Check if a given object implements the GetComments200Response interface.
 */
export function instanceOfGetComments200Response(value: object): value is GetComments200Response {
    if (!('comments' in value) || value['comments'] === undefined) return false;
    return true;
}

export function GetComments200ResponseFromJSON(json: any): GetComments200Response {
    return GetComments200ResponseFromJSONTyped(json, false);
}

export function GetComments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetComments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': ((json['comments'] as Array<any>).map(CommentFromJSON)),
    };
}

export function GetComments200ResponseToJSON(json: any): GetComments200Response {
    return GetComments200ResponseToJSONTyped(json, false);
}

export function GetComments200ResponseToJSONTyped(value?: GetComments200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': ((value['comments'] as Array<any>).map(CommentToJSON)),
    };
}

