/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * 
 * @export
 * @interface GetReplies200Response
 */
export interface GetReplies200Response {
    /**
     * 
     * @type {Array<Comment>}
     * @memberof GetReplies200Response
     */
    whatToDiscardProblemCommentReplies: Array<Comment>;
}

/**
 * Check if a given object implements the GetReplies200Response interface.
 */
export function instanceOfGetReplies200Response(value: object): value is GetReplies200Response {
    if (!('whatToDiscardProblemCommentReplies' in value) || value['whatToDiscardProblemCommentReplies'] === undefined) return false;
    return true;
}

export function GetReplies200ResponseFromJSON(json: any): GetReplies200Response {
    return GetReplies200ResponseFromJSONTyped(json, false);
}

export function GetReplies200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetReplies200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'whatToDiscardProblemCommentReplies': ((json['what_to_discard_problem_comment_replies'] as Array<any>).map(CommentFromJSON)),
    };
}

export function GetReplies200ResponseToJSON(json: any): GetReplies200Response {
    return GetReplies200ResponseToJSONTyped(json, false);
}

export function GetReplies200ResponseToJSONTyped(value?: GetReplies200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'what_to_discard_problem_comment_replies': ((value['whatToDiscardProblemCommentReplies'] as Array<any>).map(CommentToJSON)),
    };
}

